### ISSUE TITLE
http://blittle.github.io/basics/README.html 404 errors

### ISSUE THREAD

**Issue by peterblazejewicz** [blittle/chrome-dev-tools#2]
Bret, have you noticed 404 errors sometimes when going back in navigation links?
http://blittle.github.io/basics/README.html
When navigating back to already visited link and then again forward, most probably between top level nodes only like here between Introduction and Basics:
![404](https://cloud.githubusercontent.com/assets/14539/8786768/6fd3b4ee-2f30-11e5-8d48-0d2adc26c1a9.gif)
Let me know if you are able to recreate this, I could help with fixing it.
Browser: Chrome obviously
Thanks!

**Comment by blittle** [comment]
If you'd like to send a pull req that'd be awesome. I just reproduced the problem. It Seems to only happen for me when I hit the introduction link.

**Comment by blittle** [comment]
I think this is resolved with a push today.

**Comment by peterblazejewicz** [comment]
@blittle Yes, it looks like it did. 
Thanks!

**Comment by blittle** [comment]
Thank you!
